#![allow(clippy::missing_errors_doc)]
#![allow(clippy::unused_async)]
//! Inline image uploads for the rich-text fields.
//!
//! An authenticated user POSTs an image; the **bytes** are validated by magic
//! number (never the client-supplied filename or Content-Type), it is stored
//! under `uploads/` with an unguessable name, and served back so it can be
//! embedded in markdown via `![](/api/uploads/<name>)`.
//!
//! SECURITY:
//! - Only real raster images (png/jpeg/gif/webp) are accepted. **SVG is
//!   deliberately rejected**: it is XML that can carry `<script>`/`onload`, and
//!   served inline it would execute in this origin (stored XSS).
//! - Responses carry `nosniff`, a `default-src 'none'; sandbox` CSP and
//!   `Content-Disposition: inline`, so even an unexpected byte sequence cannot
//!   run script.
//! - Serving is auth-gated. In proxy mode (production) the browser sends the
//!   oauth2-proxy session cookie with `<img>` requests, so embedded images load
//!   normally. In jwt/dev mode an `<img>` cannot send a bearer token, so inline
//!   images will not load — a dev-mode limitation, not a production one.
use std::path::Path as FsPath;

use axum::http::header::{
    CONTENT_DISPOSITION, CONTENT_SECURITY_POLICY, CONTENT_TYPE, X_CONTENT_TYPE_OPTIONS,
};
use axum::response::IntoResponse;
use loco_rs::prelude::*;

use crate::security::CurrentUser;
use serde::Serialize;
use uuid::Uuid;

const UPLOAD_DIR: &str = "uploads";
const MAX_BYTES: usize = 10 * 1024 * 1024; // 10 MiB

#[derive(Serialize)]
struct UploadResponse {
    url: String,
}

/// Identifies the image type from the actual file bytes (magic number).
///
/// The client's filename and declared Content-Type are ignored on purpose —
/// both are attacker-controlled. SVG is intentionally unsupported (see module
/// docs): it would otherwise allow storing script that executes when served.
fn sniff_image(data: &[u8]) -> Option<&'static str> {
    if data.starts_with(&[0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A]) {
        return Some("png");
    }
    if data.starts_with(&[0xFF, 0xD8, 0xFF]) {
        return Some("jpg");
    }
    if data.starts_with(b"GIF87a") || data.starts_with(b"GIF89a") {
        return Some("gif");
    }
    if data.len() >= 12 && &data[0..4] == b"RIFF" && &data[8..12] == b"WEBP" {
        return Some("webp");
    }
    None
}

/// Content type for a stored file. Names are generated by us and only ever carry
/// an extension that `sniff_image` produced, so this cannot yield a scriptable
/// type; anything unexpected falls back to a non-renderable type.
fn mime_for(name: &str) -> &'static str {
    let lower = name.to_lowercase();
    if lower.ends_with(".png") {
        "image/png"
    } else if lower.ends_with(".jpg") || lower.ends_with(".jpeg") {
        "image/jpeg"
    } else if lower.ends_with(".gif") {
        "image/gif"
    } else if lower.ends_with(".webp") {
        "image/webp"
    } else {
        "application/octet-stream"
    }
}

fn is_safe_name(name: &str) -> bool {
    !name.is_empty()
        && name.len() < 128
        && !name.contains("..")
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '.' || c == '-' || c == '_')
}

#[debug_handler]
pub async fn upload(
    _user: CurrentUser,
    State(_ctx): State<AppContext>,
    mut multipart: Multipart,
) -> Result<Response> {
    while let Some(field) = multipart
        .next_field()
        .await
        .map_err(|e| Error::BadRequest(e.to_string()))?
    {
        let data = field
            .bytes()
            .await
            .map_err(|e| Error::BadRequest(e.to_string()))?;
        if data.len() > MAX_BYTES {
            return Err(Error::BadRequest("image too large (max 10 MiB)".to_string()));
        }
        // The stored type is decided by the bytes, not by anything the client said.
        let Some(ext) = sniff_image(&data) else {
            continue;
        };
        std::fs::create_dir_all(UPLOAD_DIR).map_err(|e| Error::string(&e.to_string()))?;
        let name = format!("{}.{ext}", Uuid::new_v4());
        std::fs::write(FsPath::new(UPLOAD_DIR).join(&name), &data)
            .map_err(|e| Error::string(&e.to_string()))?;
        return format::json(UploadResponse {
            url: format!("/api/uploads/{name}"),
        });
    }
    Err(Error::BadRequest(
        "no supported image in upload (png, jpeg, gif, webp)".to_string(),
    ))
}

#[debug_handler]
pub async fn serve(
    _user: CurrentUser,
    // Needed so axum infers the handler state as AppContext (CurrentUser is
    // generic over any state that AppContext can be extracted from).
    State(_ctx): State<AppContext>,
    Path(name): Path<String>,
) -> Result<Response> {
    if !is_safe_name(&name) {
        return Err(Error::NotFound);
    }
    let Ok(bytes) = std::fs::read(FsPath::new(UPLOAD_DIR).join(&name)) else {
        return Err(Error::NotFound);
    };
    Ok((
        [
            (CONTENT_TYPE, mime_for(&name)),
            // Defence in depth: never sniff, never script, never navigate.
            (X_CONTENT_TYPE_OPTIONS, "nosniff"),
            (CONTENT_SECURITY_POLICY, "default-src 'none'; sandbox"),
            (CONTENT_DISPOSITION, "inline"),
        ],
        bytes,
    )
        .into_response())
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("/api/uploads")
        .add("/", post(upload))
        .add("/{name}", get(serve))
}
